services:
  reverse-proxy:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - webapp
      - api
    networks:
      - app-net
    restart: always

  webapp:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_GRAPHQL_URL: http://localhost/graphql
    container_name: frontend_app
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=http://localhost/graphql
    expose:
      - "3000"
    networks:
      - app-net
    restart: always

  api:
    build: ./backend
    container_name: backend_api
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://db:27017/wedstack
      - REDIS_URL=redis://cache:6379/0
      - JWT_SECRET=local-development-secret-key
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX_REQUESTS=100
    expose:
      - "4000"
    depends_on:
      - db
      - cache
    networks:
      - app-net
    restart: always

  db:
    image: mongo:4.4
    container_name: mongodb_db
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-net
    restart: always

  cache:
    image: redis:alpine
    container_name: redis_cache
    volumes:
      - redis-data:/data
    networks:
      - app-net
    restart: always

volumes:
  mongodb-data:
  redis-data:

networks:
  app-net:
    driver: bridge