services:
  gateway:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - webapp
      - api
    networks:
      - app-net
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email lfariaus@gmail.com --agree-tos --no-eff-email
      -d weddingln.com -d www.weddingln.com

  webapp:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_GRAPHQL_URL: https://weddingln.com/graphql
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    container_name: frontend_app
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=https://weddingln.com/graphql
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    expose:
      - "3000"
    networks:
      - app-net
    restart: always

  api:
    build: ./backend
    container_name: backend_api
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://cache:6379/0
      - JWT_SECRET=local-development-secret-key
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX_REQUESTS=100
      - PORT=4000
    expose:
      - "4000"
    depends_on:
      - db
      - cache
    networks:
      - app-net
    restart: always

  db:
    image: mongo:4.4
    container_name: mongodb_db
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-net
    restart: always

  cache:
    image: redis:alpine
    container_name: redis_cache
    volumes:
      - redis-data:/data
    networks:
      - app-net
    restart: always

volumes:
  mongodb-data:
  redis-data:

networks:
  app-net:
    driver: bridge